trigger:
  branches:
    include:
      - main  # O la rama que usas para despliegues

pool: my_agent_pool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'  # Asegúrate de que sea la versión de Node.js que necesitas
    displayName: 'Install Node.js'

  - checkout: self  # Esto descargará el código de tu repositorio

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build --mode=test
    displayName: 'npm build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/dist'  # Asegúrate de que esta sea la ruta correcta de tu build
      TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Copia el contenido a ArtifactStagingDirectory
    displayName: 'Copy build files to artifact staging directory'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'  # Directorio que contiene los archivos de build
      includeRootFolder: false
      archiveType: 'zip'  # Empaquetar como .zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/react-build.zip'  # Nombre del archivo zip
    displayName: 'Create .zip of build files'

  - publish: '$(Build.ArtifactStagingDirectory)/react-build.zip'
    artifact: react-build
    displayName: 'Publish React build'
